In [71]:
import numpy as np
import pandas as pd

### Задание 1.1

делаю сложно, чтобы "пропускать через пальцы" 

In [72]:
proto = [1,2,3,3,1,6,8,11,10,7]
a = np.asanyarray(proto).reshape(2,-1)
a = a.T
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [73]:
b = np.mean(a,axis=0)
# ??? b[0] = 0
b

array([2. , 8.4])

### Задание 1.2

In [74]:
a_centered = a-b
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 1.3

In [75]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]

a_centered_sp = np.dot(a1,a2)

N = a1.size

a_centered_sp/(N-1)

2.0

### Задание 1.4

In [76]:
np.cov(a_centered.T)[1,0]

2.0

### Задание 2.1

In [77]:
authors = pd.DataFrame([[1, 'Тургенев'],[2, 'Чехов'],[3, 'Островский']],
                        columns=['author_id', 'author_name'] )
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [78]:
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2.2

In [79]:
authors_price = pd.merge(authors, book, how='outer', on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 2.3

In [80]:
top5  = authors_price.sort_values(by='price', ascending=False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 2.4

In [81]:

max_price = authors_price.groupby('author_id').max()[['price']]
max_price.rename(columns={'price': 'max_price'}, inplace = True)

max_price

max_price
author_id           
1                450
2                500
3                370

In [82]:
min_price = authors_price.groupby('author_id').min()[['price']]
min_price.rename(columns={'price': 'min_price'}, inplace = True)

min_price

min_price
author_id           
1                300
2                450
3                290

In [83]:
mean_price = authors_price.groupby('author_id').mean()[['price']]
mean_price.rename(columns={'price': 'mean_price'}, inplace = True)

mean_price

mean_price
author_id            
1          366.666667
2          475.000000
3          330.000000

In [84]:
authors_stat = authors.merge(max_price, how='outer', on='author_id')\
    .merge(min_price, how='outer', on='author_id')\
    .merge(mean_price, how='outer', on='author_id')

authors_stat

author_id author_name  max_price  min_price  mean_price
0          1    Тургенев        450        300  366.666667
1          2       Чехов        500        450  475.000000
2          3  Островский        370        290  330.000000

### Задание 2.5

In [113]:
cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price = authors_price.assign(cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'])
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [115]:
?pd.pivot_table

In [118]:
book_info = authors_price.pivot_table('price', index='author_name', columns='cover', aggfunc='sum', fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [120]:
pd.to_pickle(book_info, filepath_or_buffer='book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')

In [123]:
diff = book_info.append(book_info2).drop_duplicates(keep=False)
diff

Empty DataFrame
Columns: [мягкая, твердая]
Index: []