In [1]:
import numpy as np

### Задание 1

делаю сложно, чтобы "пропускать через пальцы" 

In [14]:
proto = [1,2,3,3,1,6,8,11,10,7]
a = np.asanyarray(proto).reshape(2,-1)
a = a.T
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [19]:
b = np.mean(a,axis=0)
# ??? b[0] = 0
b

array([2. , 8.4])

### Задание 2

In [21]:
a_centered = a-b
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [30]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]

a_centered_sp = np.dot(a1,a2)

N = a1.size

a_centered_sp/(N-1)

2.0

### Задание 4

In [33]:
np.cov(a_centered.T)

array([[1. , 2. ],
       [2. , 4.3]])