In [113]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [114]:
data = pd.read_csv('https://storage.googleapis.com/kagglesdsdata/competitions/3136/26502/train.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1632886018&Signature=rnYENhSIyJJLFqVB8c8jRTR9MBXA%2FloUKDjBC%2Fofh%2Bx%2BGmt74x2WLu%2Bs5VSSoUjnbdVQ68sbRYvs%2BphUrnx7NmN%2BjLyFV6B5E%2BuG5v%2BxDDk6bGl1xgXORyYR5uRjozidySoso82SjOo8V6I%2B3CziaG1pgEPOwJqKa%2F3l1PJONNZkwkreJQcb64BgUysGFojK3sWP7JLcmidSH2QRh%2Bxt7mGanAhTb2zdkfK9FGhsf5scOPQP1JYlAyuU%2F4amq2rWJpfxBDjc%2BWHpY1MPIKNHZCWlNS0c3XsgQdayDqj07jCWzrN2dmkgG2GMe3XgvWVMoudkYRTDrmmx86vhBmmMHA%3D%3D&response-content-disposition=attachment%3B+filename%3Dtrain.csv')

In [115]:
data.set_index('PassengerId')
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [116]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [117]:
target = 'Survived'

In [118]:
y = data[target]
x = data.drop(target, axis=1)

In [119]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Name         891 non-null    object 
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB


In [120]:
x = x.drop(['Cabin', 'Name', 'Ticket'], axis=1)

In [121]:
mean_age = x['Age'].mean()
mean_age

29.69911764705882

In [122]:
x['Age'] = x['Age'].fillna(mean_age)
x['Age'].unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5 

In [123]:
embarket_mode = x['Embarked'].mode()[0]
x['Embarked'].fillna(embarket_mode, inplace=True)
x['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [124]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Sex          891 non-null    object 
 3   Age          891 non-null    float64
 4   SibSp        891 non-null    int64  
 5   Parch        891 non-null    int64  
 6   Fare         891 non-null    float64
 7   Embarked     891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [125]:
x['Sex'] = (x['Sex'] == 'female').astype(int)

In [126]:
x['Sex'].value_counts()

0    577
1    314
Name: Sex, dtype: int64

In [127]:
x = pd.get_dummies(x)

In [128]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Sex          891 non-null    int32  
 3   Age          891 non-null    float64
 4   SibSp        891 non-null    int64  
 5   Parch        891 non-null    int64  
 6   Fare         891 non-null    float64
 7   Embarked_C   891 non-null    uint8  
 8   Embarked_Q   891 non-null    uint8  
 9   Embarked_S   891 non-null    uint8  
dtypes: float64(2), int32(1), int64(4), uint8(3)
memory usage: 48.0 KB


In [129]:
x.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  \
0            1       3    0  22.0      1      0   7.2500           0   
1            2       1    1  38.0      1      0  71.2833           1   
2            3       3    1  26.0      0      0   7.9250           0   
3            4       1    1  35.0      1      0  53.1000           0   
4            5       3    0  35.0      0      0   8.0500           0   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [130]:
x['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [131]:
x['Pclass'] = x['Pclass'].astype('category')

In [132]:
x = pd.get_dummies(x)

In [133]:
x.columns

Index(['PassengerId', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S', 'Pclass_1', 'Pclass_2', 'Pclass_3'],
      dtype='object')

In [134]:
x.head()

PassengerId  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0            1    0  22.0      1      0   7.2500           0           0   
1            2    1  38.0      1      0  71.2833           1           0   
2            3    1  26.0      0      0   7.9250           0           0   
3            4    1  35.0      1      0  53.1000           0           0   
4            5    0  35.0      0      0   8.0500           0           0   

   Embarked_S  Pclass_1  Pclass_2  Pclass_3  
0           1         0         0         1  
1           0         1         0         0  
2           1         0         0         1  
3           1         1         0         0  
4           1         0         0         1

In [135]:
x_train, x_valid, y_train, y_valid = train_test_split(x, y, test_size=.25, random_state=42)

In [136]:
lr = LogisticRegression()

In [137]:
lr.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [138]:
y_pred = lr.predict(x_valid)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0], dtype=int64)

In [139]:
from sklearn.metrics import accuracy_score

In [140]:
accuracy_score(y_valid, y_pred)

0.7937219730941704

In [141]:
y_pred_train = lr.predict(x_train)
accuracy_score(y_train, y_pred_train)

0.812874251497006

In [142]:
y_proba = lr.predict_proba(x_valid)
y_proba

array([[0.87830022, 0.12169978],
       [0.7325323 , 0.2674677 ],
       [0.85411973, 0.14588027],
       [0.08244227, 0.91755773],
       [0.27508707, 0.72491293],
       [0.08345352, 0.91654648],
       [0.33933644, 0.66066356],
       [0.90728889, 0.09271111],
       [0.255379  , 0.744621  ],
       [0.11527068, 0.88472932],
       [0.72049332, 0.27950668],
       [0.9292184 , 0.0707816 ],
       [0.61523954, 0.38476046],
       [0.85609037, 0.14390963],
       [0.76581649, 0.23418351],
       [0.07119323, 0.92880677],
       [0.72084838, 0.27915162],
       [0.31369156, 0.68630844],
       [0.67284273, 0.32715727],
       [0.7342763 , 0.2657237 ],
       [0.88835487, 0.11164513],
       [0.65020842, 0.34979158],
       [0.41502668, 0.58497332],
       [0.85970752, 0.14029248],
       [0.89486859, 0.10513141],
       [0.91768975, 0.08231025],
       [0.60845549, 0.39154451],
       [0.71463508, 0.28536492],
       [0.92202693, 0.07797307],
       [0.42754529, 0.57245471],
       [0.

In [143]:
x_train.to_pickle('x_train.plk')
y_train.to_pickle('y_train.plk')

x_valid.to_pickle('x_valid.plk')
y_valid.to_pickle('y_valid.plk')